// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxEV-mwZcgKV4RH-w-5XMyxASdDAHPdE',
    appId: '1:906077851275:web:897391cc2d4e27196fce8e',
    messagingSenderId: '906077851275',
    projectId: 'newproject-52066',
    authDomain: 'newproject-52066.firebaseapp.com',
    storageBucket: 'newproject-52066.firebasestorage.app',
    measurementId: 'G-V61MYFKM2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtdioaUuZHADJBXXEDhxBKDKqasBrfAY',
    appId: '1:906077851275:android:e4ccaf54db4308d46fce8e',
    messagingSenderId: '906077851275',
    projectId: 'newproject-52066',
    storageBucket: 'newproject-52066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDul4yJrC4hmow6UjkECq_qxTdRDVrJGnk',
    appId: '1:906077851275:ios:9424bde2fb29e3f06fce8e',
    messagingSenderId: '906077851275',
    projectId: 'newproject-52066',
    storageBucket: 'newproject-52066.firebasestorage.app',
    androidClientId: '906077851275-2ehq81i8gqe906pv3klblkt1cgmfisgd.apps.googleusercontent.com',
    iosClientId: '906077851275-m1r3buud25hjdbkbcga54lcrt8p5kjub.apps.googleusercontent.com',
    iosBundleId: 'com.example.bussinessManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDul4yJrC4hmow6UjkECq_qxTdRDVrJGnk',
    appId: '1:906077851275:ios:9424bde2fb29e3f06fce8e',
    messagingSenderId: '906077851275',
    projectId: 'newproject-52066',
    storageBucket: 'newproject-52066.firebasestorage.app',
    androidClientId: '906077851275-2ehq81i8gqe906pv3klblkt1cgmfisgd.apps.googleusercontent.com',
    iosClientId: '906077851275-m1r3buud25hjdbkbcga54lcrt8p5kjub.apps.googleusercontent.com',
    iosBundleId: 'com.example.bussinessManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACxEV-mwZcgKV4RH-w-5XMyxASdDAHPdE',
    appId: '1:906077851275:web:022105dc68d7ab026fce8e',
    messagingSenderId: '906077851275',
    projectId: 'newproject-52066',
    authDomain: 'newproject-52066.firebaseapp.com',
    storageBucket: 'newproject-52066.firebasestorage.app',
    measurementId: 'G-6EMFSZ2YNB',
  );

}
